<a href="https://colab.research.google.com/github/chltjs1921/2024_modeling_practice/blob/main/dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tensor>dataset>dataloader

In [1]:
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, datasets
import numpy as np

In [2]:
!pip install rdkit
!pip install torch_geometric

# Optional dependencies:
!pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.3.0+cu121.html

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.1/33.1 MB 66.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.2/64.2 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 42.7 MB/s eta 0:00:00
Looking in links: https://data.pyg.org/whl/torch-2.3.0+cu121.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 21.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 55.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 45.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 51.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 947.1/947.1 kB 35.6 MB/s eta 0:00:00


In [ ]:
rxn_ex_df_catalyst_fps = np.load('/content/drive/MyDrive/2024_modeling/rxn_ex_df_catalyst_fps.npy', allow_pickle=True)

In [ ]:
type(rxn_ex_df_catalyst_fps)

numpy.ndarray

In [ ]:
#convert ndarray to tensor
rxn_ex_df_catalyst_fps_tensor = torch.from_numpy(rxn_ex_df_catalyst_fps)

In [ ]:
type(rxn_ex_df_catalyst_fps_tensor)

torch.Tensor

In [3]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem

In [4]:
rxn_ex_df = pd.read_csv('/content/drive/MyDrive/2024_modeling/ETHmodlab-lsfml-d0178f1/lsfml/data/experimental_rxndata.csv')
rxn_ex_df

rxn_id                                       educt  \
0    ELN036496-175_1_1_D6  C1(=C(C)ON=C1C(C=C(F)C2)=CC=2)C3C=C[NH]N=3   
1    ELN036496-175_1_1_D5  C1(=C(C)ON=C1C(C=C(F)C2)=CC=2)C3C=C[NH]N=3   
2    ELN036496-175_1_1_D4  C1(=C(C)ON=C1C(C=C(F)C2)=CC=2)C3C=C[NH]N=3   
3    ELN036496-175_1_1_D3  C1(=C(C)ON=C1C(C=C(F)C2)=CC=2)C3C=C[NH]N=3   
4    ELN036496-175_1_1_D2  C1(=C(C)ON=C1C(C=C(F)C2)=CC=2)C3C=C[NH]N=3   
..                    ...                                         ...   
951  ELN036496-112_1_1_A5                       O(C1=CC=CC(OC)=C1OC)C   
952  ELN036496-112_1_1_A4                       O(C1=CC=CC(OC)=C1OC)C   
953  ELN036496-112_1_1_A3                       O(C1=CC=CC(OC)=C1OC)C   
954  ELN036496-112_1_1_A2                       O(C1=CC=CC(OC)=C1OC)C   
955  ELN036496-112_1_1_A1                       O(C1=CC=CC(OC)=C1OC)C   

     rxn_scale_mol  rxn_temp_C  rxn_time_h rxn_atm  rxn_c_moll  \
0           0.0001          80          18      N2         0.2   
1           0.0001          80          18      N2         0.2   
2           0.0001          80          18      N2         0.2   
3           0.0001          80          18      N2         0.2   
4           0.0001          80          18      N2         0.2   
..             ...         ...         ...     ...         ...   
951         0.0001          80          18      N2         0.2   
952         0.0001          80          18      N2         0.2   
953         0.0001          80          18      N2         0.2   
954         0.0001          80          18      N2         0.2   
955         0.0001          80          18      N2         0.2   

                                              catalyst  catalyst_eq  \
0    C[O+]1[Ir-]2[O+](C)[Ir-]12.C3CC=CCCC=C3.C4CC=C...        0.025   
1    C[O+]1[Ir-]2[O+](C)[Ir-]12.C3CC=CCCC=C3.C4CC=C...        0.025   
2    C[O+]1[Ir-]2[O+](C)[Ir-]12.C3CC=CCCC=C3.C4CC=C...        0.025   
3    C[O+]1[Ir-]2[O+](C)[Ir-]12.C3CC=CCCC=C3.C4CC=C...        0.025   
4    C[O+]1[Ir-]2[O+](C)[Ir-]12.C3CC=CCCC=C3.C4CC=C...        0.025   
..                                                 ...          ...   
951  C[O+]1[Ir-]2[O+](C)[Ir-]12.C3CC=CCCC=C3.C4CC=C...        0.025   
952  C[O+]1[Ir-]2[O+](C)[Ir-]12.C3CC=CCCC=C3.C4CC=C...        0.025   
953  C[O+]1[Ir-]2[O+](C)[Ir-]12.C3CC=CCCC=C3.C4CC=C...        0.025   
954  C[O+]1[Ir-]2[O+](C)[Ir-]12.C3CC=CCCC=C3.C4CC=C...        0.025   
955  C[O+]1[Ir-]2[O+](C)[Ir-]12.C3CC=CCCC=C3.C4CC=C...        0.025   

                                         ligand  ligand_eq  \
0       N=1C=C(C(=C2C=CC3=C(N=CC(=C3C)C)C12)C)C       0.05   
1                   N=1C=CC=C2C=CC=3C=CC=NC3C12       0.05   
2                  N=1C=CC(=CC1C=2N=CC=C(C2)C)C       0.05   
3    N=1C=CC(=CC1C=2N=CC=C(C2)C(C)(C)C)C(C)(C)C       0.05   
4                        N1=CC=CC2=CC=CC(N)=C12       0.05   
..                                          ...        ...   
951                 N=1C=CC=C2C=CC=3C=CC=NC3C12       0.05   
952                N=1C=CC(=CC1C=2N=CC=C(C2)C)C       0.05   
953  N=1C=CC(=CC1C=2N=CC=C(C2)C(C)(C)C)C(C)(C)C       0.05   
954                      N1=CC=CC2=CC=CC(N)=C12       0.05   
955   N=1C=CC=CC1C=NN(CC=2C=CC=CC2)CC=3C=CC=CC3       0.05   

                                    reagent  reagent_eq   solvent  \
0    O1B(OC(C)(C)C1(C)C)B2OC(C)(C)C(O2)(C)C           1      N#CC   
1    O1B(OC(C)(C)C1(C)C)B2OC(C)(C)C(O2)(C)C           1      N#CC   
2    O1B(OC(C)(C)C1(C)C)B2OC(C)(C)C(O2)(C)C           1      N#CC   
3    O1B(OC(C)(C)C1(C)C)B2OC(C)(C)C(O2)(C)C           1      N#CC   
4    O1B(OC(C)(C)C1(C)C)B2OC(C)(C)C(O2)(C)C           1      N#CC   
..                                      ...         ...       ...   
951  O1B(OC(C)(C)C1(C)C)B2OC(C)(C)C(O2)(C)C           1  C1CCCCC1   
952  O1B(OC(C)(C)C1(C)C)B2OC(C)(C)C(O2)(C)C           1  C1CCCCC1   
953  O1B(OC(C)(C)C1(C)C)B2OC(C)(C)C(O2)(C)C           1  C1CCCCC1   
954  O1B(OC(C)(C)C1(C)C)B2OC(C)(C)C(O2)(C)C           1  C1CC

In [5]:
rxn_ex_df.describe()

rxn_scale_mol  rxn_temp_C  rxn_time_h  rxn_c_moll  catalyst_eq  \
count   9.560000e+02       956.0       956.0       956.0      956.000   
mean    1.000000e-04        80.0        18.0         0.2        0.025   
std     1.355962e-20         0.0         0.0         0.0        0.000   
min     1.000000e-04        80.0        18.0         0.2        0.025   
25%     1.000000e-04        80.0        18.0         0.2        0.025   
50%     1.000000e-04        80.0        18.0         0.2        0.025   
75%     1.000000e-04        80.0        18.0         0.2        0.025   
max     1.000000e-04        80.0        18.0         0.2        0.025   

       ligand_eq  reagent_eq  solvent_ratio      yes_no     mono_bo  \
count     956.00       956.0          956.0  956.000000  956.000000   
mean        0.05         1.0            1.0    0.265690    0.115805   
std         0.00         0.0            0.0    0.441931    0.251452   
min         0.05         1.0            1.0    0.000000    0.000000   
25%         0.05         1.0            1.0    0.000000    0.000000   
50%         0.05         1.0            1.0    0.000000    0.000000   
75%         0.05         1.0            1.0    1.000000    0.020000   
max         0.05         1.0            1.0    1.000000    1.000000   

            di_bo      non_bo        drug  
count  956.000000  956.000000  956.000000  
mean     0.005220    0.879017    0.574268  
std      0.031418    0.260348    0.494712  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.977500    0.000000  
50%      0.000000    1.000000    1.000000  
75%      0.000000    1.000000    1.000000  
max      0.430000    1.000000    1.000000

In [10]:
rxn_ex_df.drug.value_counts() #yes_no, drug는 0과 1. bo머시기들은 전부 회귀

drug
1    549
0    407
Name: count, dtype: int64

In [ ]:
from rdkit import Chem
from rdkit.Chem import AllChem
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader

class molecular_data_process_loader(Dataset):
    def __init__(self, df):
        self.df = df

        self.mfpgen = Chem.rdFingerprintGenerator.GetMorganGenerator(radius=2,fpSize=256)

    def __len__(self):
        return self.df.shape[0]

    def __getitem__(self, idx):
        v_educt = self.df.iloc[idx]['educt']
        v_educt = self.mfpgen.GetFingerprintAsNumPy(Chem.rdmolops.AddHs(Chem.MolFromSmiles(v_educt)))
        v_educt = torch.from_numpy(v_educt).type(torch.LongTensor)

        v_catalyst = self.df.iloc[idx]['catalyst']
        v_catalyst = self.mfpgen.GetFingerprintAsNumPy(Chem.rdmolops.AddHs(Chem.MolFromSmiles(v_catalyst)))
        v_catalyst = torch.from_numpy(v_catalyst).type(torch.LongTensor)

        v_ligand = self.df.iloc[idx]['ligand']
        v_ligand = self.mfpgen.GetFingerprintAsNumPy(Chem.rdmolops.AddHs(Chem.MolFromSmiles(v_ligand)))
        v_ligand = torch.from_numpy(v_ligand).type(torch.LongTensor)

        v_reagent = self.df.iloc[idx]['reagent']
        v_reagent = self.mfpgen.GetFingerprintAsNumPy(Chem.rdmolops.AddHs(Chem.MolFromSmiles(v_reagent)))
        v_reagent = torch.from_numpy(v_reagent).type(torch.LongTensor)

        v_solvent = self.df.iloc[idx]['solvent']
        v_solvent = self.mfpgen.GetFingerprintAsNumPy(Chem.rdmolops.AddHs(Chem.MolFromSmiles(v_solvent)))
        v_solvent = torch.from_numpy(v_solvent).type(torch.LongTensor)

        v_conc = torch.cat((v_educt, v_catalyst, v_ligand, v_reagent, v_solvent), 0) #가로로 길게
        return v_educt, v_catalyst, v_ligand, v_reagent, v_solvent, v_conc

In [ ]:
loader = molecular_data_process_loader(rxn_ex_df)

In [ ]:
for v_educt, v_catalyst, v_ligand, v_reagent, v_solvent, v_conc in loader:
  print(v_educt.shape)
  print(v_catalyst.shape)
  print(v_ligand.shape)
  print(v_reagent.shape)
  print(v_solvent.shape)
  print(v_conc.shape)
  print(type(v_conc))
  break

torch.Size([256])
torch.Size([256])
torch.Size([256])
torch.Size([256])
torch.Size([256])
torch.Size([1280])
<class 'torch.Tensor'>


In [ ]:
v_conc

tensor([0, 0, 0,  ..., 0, 0, 0])

In [ ]:
rxn_ex_df_educp_fps = np.load('/content/drive/MyDrive/2024_modeling/rxn_ex_df_educp_fps.npy', allow_pickle=True)

In [ ]:
rxn_ex_df_educp_fps[0]

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [ ]:
class rxn_data_process_loader(Dataset):
    def __init__(self, df):
        self.df = df

    def __len__(self):
        return self.df.shape[0]

    def __getitem__(self, idx):
        rxn = self.df.iloc[idx][['rxn_scale_mol', 'rxn_temp_C', 'rxn_time_h','rxn_c_moll', 'catalyst_eq', 'ligand_eq', 'reagent_eq', 'solvent_ratio']]
        rxn = pd.to_numeric(rxn, errors='coerce')
        rxn = torch.torch.from_numpy(rxn.values).type(torch.FloatTensor)
        return rxn

In [ ]:
rxn_loader = rxn_data_process_loader(rxn_ex_df)

In [ ]:
for rxn in rxn_loader:
  print(rxn)
  print(type(rxn))
  break

tensor([1.0000e-04, 8.0000e+01, 1.8000e+01, 2.0000e-01])
<class 'torch.Tensor'>


In [59]:
from collections import Counter

list_dict_ligand = {}
list_counter = Counter(list(rxn_ex_df['ligand']))

for idx, x in enumerate(list_counter):
    list_dict_ligand[x] = idx

print(list_dict_ligand)

#dictinaray의 value만 따로 추출
print(list(list_dict_ligand.values()))

{'N=1C=C(C(=C2C=CC3=C(N=CC(=C3C)C)C12)C)C': 0, 'N=1C=CC=C2C=CC=3C=CC=NC3C12': 1, 'N=1C=CC(=CC1C=2N=CC=C(C2)C)C': 2, 'N=1C=CC(=CC1C=2N=CC=C(C2)C(C)(C)C)C(C)(C)C': 3, 'N1=CC=CC2=CC=CC(N)=C12': 4, 'N=1C=CC=CC1C=NN(CC=2C=CC=CC2)CC=3C=CC=CC3': 5}
[0, 1, 2, 3, 4, 5]


In [60]:
list_dict_sol = {}
list_counter_sol = Counter(list(rxn_ex_df['solvent']))

for idx, x in enumerate(list_counter_sol):
    list_dict_sol[x] = idx

print(list_dict_sol)

#dictinaray의 value만 따로 추출
print(list(list_dict_sol.values()))

{'N#CC': 0, 'O(C)C1CCCC1': 1, 'O1CCCC1C': 2, 'C1CCCCC1': 3}
[0, 1, 2, 3]


데이터로더에 드갈거(getitem)  
물질들 descriptor  
반응 조건들  
정답들

In [85]:
class data_process_loader(Dataset):
    def __init__(self, df):
        self.df = df

        self.mfpgen = Chem.rdFingerprintGenerator.GetMorganGenerator(radius=2,fpSize=256) #이 파라미터들도 변수에 포함?
        #mfpgen 여러개: 파라미터 독립적

        self.list_dict_ligand = {}
        list_counter_ligand = Counter(list(df['ligand']))
        for idx, x in enumerate(list_counter_ligand):
            self.list_dict_ligand[x] = idx

        self.list_dict_sol = {}
        list_counter_sol = Counter(list(df['solvent']))
        for idx, x in enumerate(list_counter_sol):
            self.list_dict_sol[x] = idx

    def __len__(self):
        return self.df.shape[0]

    def __getitem__(self, idx):
        v_educt = self.df.iloc[idx]['educt']
        v_educt = self.mfpgen.GetFingerprintAsNumPy(Chem.rdmolops.AddHs(Chem.MolFromSmiles(v_educt)))
        v_educt = torch.from_numpy(v_educt).type(torch.Tensor)

        v_catalyst = self.df.iloc[idx]['catalyst']
        v_catalyst = self.mfpgen.GetFingerprintAsNumPy(Chem.rdmolops.AddHs(Chem.MolFromSmiles(v_catalyst)))
        v_catalyst = torch.from_numpy(v_catalyst).type(torch.LongTensor)

        v_ligand = self.df.iloc[idx]['ligand']
        v_ligand_dict = torch.tensor(self.list_dict_ligand[v_ligand]).type(torch.LongTensor)
        # v_ligand = self.mfpgen.GetFingerprintAsNumPy(Chem.rdmolops.AddHs(Chem.MolFromSmiles(v_ligand)))
        # v_ligand = torch.from_numpy(v_ligand).type(torch.LongTensor)


        v_reagent = self.df.iloc[idx]['reagent']
        v_reagent = self.mfpgen.GetFingerprintAsNumPy(Chem.rdmolops.AddHs(Chem.MolFromSmiles(v_reagent)))
        v_reagent = torch.from_numpy(v_reagent).type(torch.LongTensor)

        v_solvent = self.df.iloc[idx]['solvent']
        v_solvent_dict = torch.tensor(self.list_dict_sol[v_solvent]).type(torch.LongTensor)
        # v_solvent = self.mfpgen.GetFingerprintAsNumPy(Chem.rdmolops.AddHs(Chem.MolFromSmiles(v_solvent)))
        # v_solvent = torch.from_numpy(v_solvent).type(torch.LongTensor)

        #v_conc = torch.cat((v_educt, v_catalyst, v_ligand, v_reagent, v_solvent), 0) #가로로 길게

        rxn = self.df.iloc[idx][['rxn_scale_mol', 'rxn_temp_C', 'rxn_time_h','rxn_c_moll', 'catalyst_eq', 'ligand_eq', 'reagent_eq', 'solvent_ratio']]
        rxn = pd.to_numeric(rxn, errors='coerce')
        rxn = torch.from_numpy(rxn.values).type(torch.FloatTensor)

        prod = self.df.iloc[idx][['yes_no',	'mono_bo',	'di_bo',	'non_bo',	'drug']]
        prod = pd.to_numeric(prod, errors='coerce')
        prod = torch.from_numpy(prod.values).type(torch.FloatTensor)
        #이 다섯개도 따로? >> prod를 풀기(unpack directly)
        return v_educt, v_ligand_dict, v_solvent_dict, prod

In [86]:
loader = data_process_loader(rxn_ex_df)

In [87]:
for v_educt, v_ligand_dict, v_solvent_dict, prod in loader:
    print(v_educt)
    print(v_educt.shape)
    print(v_ligand_dict)
    print(type(v_ligand_dict))
    print(v_solvent_dict)
    print(prod)
    break

tensor([0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 

In [57]:
for v_educt, v_ligand, v_solvent, prod in loader:
    yes, mono, di, non, drug = prod # Unpack prod directly here
    print(yes, mono, di, non, drug)
    break

tensor(0.) tensor(0.) tensor(0.) tensor(1.) tensor(0.)


In [ ]:
v_educt

tensor([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0])

data 끝. 이제 모델링

In [126]:
import torch.nn as nn

class basemodel(nn.Module):
    def __init__(self, fp_dim=256, mlp_dim=512, kernel_dim=64, embeddings_dim=64, dropout=0.1):
        super(basemodel, self).__init__()

        self.embeddings_dim = embeddings_dim
        self.kernel_dim = kernel_dim
        self.mlp_dim = mlp_dim
        self.fp_dim = fp_dim

        self.dropout = nn.Dropout(dropout)

        self.mlp_descriptor = nn.Sequential(
            nn.Linear(self.fp_dim, self.kernel_dim * 2),
            self.dropout,
            nn.SiLU(),
            nn.Linear(self.kernel_dim * 2, self.kernel_dim * 2),
            nn.SiLU(),
            nn.Linear(self.kernel_dim * 2, self.kernel_dim),
        )

        self.mlp_condition_lig = nn.Embedding(num_embeddings=6, embedding_dim=self.embeddings_dim)
        self.mlp_condition_sol = nn.Embedding(num_embeddings=4, embedding_dim=self.embeddings_dim)

        nn.init.xavier_uniform_(self.mlp_condition_lig.weight)
        nn.init.xavier_uniform_(self.mlp_condition_sol.weight)

        self.post_pooling_mlp_input_dim = self.kernel_dim + self.embeddings_dim * 2

        self.mlp_output = nn.Sequential(
            nn.Linear(self.post_pooling_mlp_input_dim, self.mlp_dim),
            self.dropout,
            nn.SiLU(),
            nn.Linear(self.mlp_dim, self.mlp_dim),
            nn.SiLU(),
            nn.Linear(self.mlp_dim, self.mlp_dim),
            nn.SiLU(),
            nn.Linear(self.mlp_dim, 1),
        )

    def forward(self, v_educt, v_lig, v_sol):
        x_conc = self.mlp_descriptor(v_educt) #educt만으로
        # print("Shape of self.mlp_condition_lig(v_lig):", self.mlp_condition_lig(v_lig).shape)
        # print("Shape of self.mlp_condition_sol(v_sol):", self.mlp_condition_sol(v_sol).shape)
        x_rxn = torch.cat((self.mlp_condition_lig(v_lig), self.mlp_condition_sol(v_sol)), 0) #lig, sol 임베딩 후 cat. 임베딩 전처리는?
        # print("Shape of x_conc:", x_conc.shape)
        # print("Shape of x_rxn:", x_rxn.shape)

        x = torch.cat((x_conc, x_rxn), 0)
        # print("Shape of x:", x.shape)
        output = self.mlp_output(x)
        return output

In [16]:
!pip install torchinfo

In [17]:
from torchinfo import summary

In [89]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [90]:
def create_fold(df, fold_seed, frac):

    train_frac, val_frac, test_frac = frac

    test = df.sample(frac=test_frac, random_state=fold_seed, replace=False)
    train_val = df.drop(test.index)

    val = train_val.sample(frac=val_frac/(train_frac+val_frac), random_state=fold_seed, replace=False)
    train = train_val.drop(val.index)

    return train, val, test

In [91]:
train, val, test = create_fold(rxn_ex_df, 42, [0.7, 0.1, 0.2])

In [92]:
train_dataset = data_process_loader(train)
val_dataset = data_process_loader(val)
test_dataset = data_process_loader(test)

In [136]:
summary(basemodel(), col_names=["num_params", "trainable"],
        col_width=20, row_settings=["var_names"])

Layer (type (var_name))                  Param #              Trainable
basemodel (basemodel)                    --                   True
├─Dropout (dropout)                      --                   --
├─Sequential (mlp_descriptor)            --                   True
│    └─Linear (0)                        32,896               True
│    └─Dropout (1)                       --                   --
│    └─SiLU (2)                          --                   --
│    └─Linear (3)                        16,512               True
│    └─SiLU (4)                          --                   --
│    └─Linear (5)                        8,256                True
├─Embedding (mlp_condition_lig)          384                  True
├─Embedding (mlp_condition_sol)          256                  True
├─Sequential (mlp_output)                --                   True
│    └─Linear (0)                        98,816               True
│    └─Dropout (1)                       --                   --


In [106]:
model = basemodel()
model.to(device)

basemodel(
  (dropout): Dropout(p=0.1, inplace=False)
  (mlp_descriptor): Sequential(
    (0): Linear(in_features=256, out_features=128, bias=True)
    (1): Dropout(p=0.1, inplace=False)
    (2): SiLU()
    (3): Linear(in_features=128, out_features=128, bias=True)
    (4): SiLU()
    (5): Linear(in_features=128, out_features=64, bias=True)
  )
  (mlp_condition_lig): Embedding(6, 64)
  (mlp_condition_sol): Embedding(4, 64)
  (mlp_output): Sequential(
    (0): Linear(in_features=192, out_features=512, bias=True)
    (1): Dropout(p=0.1, inplace=False)
    (2): SiLU()
    (3): Linear(in_features=512, out_features=512, bias=True)
    (4): SiLU()
    (5): Linear(in_features=512, out_features=512, bias=True)
    (6): SiLU()
    (7): Linear(in_features=512, out_features=1, bias=True)
  )
)

In [31]:
list_counter = Counter(list(rxn_ex_df['ligand']))
print(list_counter)

Counter({'N=1C=C(C(=C2C=CC3=C(N=CC(=C3C)C)C12)C)C': 160, 'N=1C=CC=C2C=CC=3C=CC=NC3C12': 160, 'N=1C=CC(=CC1C=2N=CC=C(C2)C)C': 159, 'N=1C=CC(=CC1C=2N=CC=C(C2)C(C)(C)C)C(C)(C)C': 159, 'N1=CC=CC2=CC=CC(N)=C12': 159, 'N=1C=CC=CC1C=NN(CC=2C=CC=CC2)CC=3C=CC=CC3': 159})


In [127]:
model = basemodel()
model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()

In [129]:
len(train_dataset)

669

In [145]:
#train
epoch = 5

for epoch in range(epoch):
    model.train()

    for i, (v_educt, v_ligand_dict, v_solvent_dict, prod) in enumerate(train_dataset):
        v_educt = v_educt.float().to(device)
        v_ligand = v_ligand_dict.to(device)
        v_solvent = v_solvent_dict.to(device)
        prod = prod.to(device)
        yes, mono, di, non, drug = prod #mono, di, non이 regression. yes, drug가 binary classification
        print(mono)
        print(type(mono))
        print(mono.shape)

        score = model(v_educt, v_ligand, v_solvent)
        print(score)
        print(type(score))
        print(score.shape)

        loss = criterion(score, mono.unsqueeze(0))
        print(loss)
        print(type(loss))
        print(loss.shape)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
<class 'torch.Tensor'>
torch.Size([])
tensor(0., device='cuda:0')
<class 'torch.Tensor'>
torch.Size([])
Shape of self.mlp_condition_lig(v_lig): torch.Size([64])
Shape of self.mlp_condition_sol(v_sol): torch.Size([64])
Shape of x_conc: torch.Size([64])
Shape of x_rxn: torch.Size([128])
Shape of x: torch.Size([192])
tensor([0.0230], device='cuda:0', grad_fn=<ViewBackward0>)
<class 'torch.Tensor'>
torch.Size([1])
tensor(0.0005, device='cuda:0', grad_fn=<MseLossBackward0>)
<class 'torch.Tensor'>
torch.Size([])
tensor(0., device='cuda:0')
<class 'torch.Tensor'>
torch.Size([])
Shape of self.mlp_condition_lig(v_lig): torch.Size([64])
Shape of self.mlp_condition_sol(v_sol): torch.Size([64])
Shape of x_conc: torch.Size([64])
Shape of x_rxn: torch.Size([128])
Shape of x: torch.Size([192])
tensor([-0.0080], device='cuda:0', grad_fn=<ViewBackward0>)
<class 'torch.Tensor'>
torch.Size([1])
tensor(6.4447e-05, device='cuda:0', grad_fn=<MseLossBackward0>)
<class 'tor